language: go

sudo: false

branches:
  except:
    # skip tags and master build, since we are building branch v*-edge and
    # master merge PR that is enough for consistenty check and release.
    # Let's use Travis CI resources optimally for aah framework.
    - master
    - /^v[0-9.]+$/

go:
  - 1.9.x
  - 1.10.x
  - tip

go_import_path: aahframework.org/valpar.v0

install:
  - go get -t -v ./...

script:
  - bash <(curl -s https://aahframework.org/go-test)

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
